# Generated by Django 4.1.2 on 2022-10-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_jefatura',
            field=models.BooleanField(default=False, help_text='Indica si es jefatura'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_secretaria',
            field=models.BooleanField(default=False, help_text='Indica si es secretaria'),
        ),
    ]
