# Generated by Django 4.1.2 on 2022-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_usuario_es_jefatura_alter_usuario_es_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_cajera',
            field=models.BooleanField(default=False, help_text='Indica si es cajera'),
        ),
    ]
