# Generated by Django 4.1.2 on 2022-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_usuario_es_agente_usuario_es_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_primeraVez',
            field=models.BooleanField(default=False, help_text='Indica si es primer login'),
        ),
    ]
