# Generated by Django 4.1.2 on 2022-11-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('pagado', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'solicitud_pago',
            },
        ),
    ]
