# Generated by Django 4.1.2 on 2022-10-24 21:02

import cliente.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id_actividadEconomica', models.AutoField(primary_key=True, serialize=False, verbose_name='Actividad Economica ID')),
                ('nombreProfesion', models.CharField(max_length=50, verbose_name='Profesion u Ocupacion')),
                ('lugarTrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Lugar de trabajo o Negocio')),
                ('paisTrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais de Trabajo')),
                ('ciudadTrabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad de Trabajo')),
                ('telefono', phone_field.models.PhoneField(blank=True, max_length=13, null=True, verbose_name='Telefono de lugar de trabajo')),
                ('asociacion', models.CharField(blank=True, help_text='Ayuda: <em>Puede ser asociacion economica o social</em>.', max_length=50, null=True, verbose_name='Asociaciones a la que pertenece')),
            ],
            options={
                'db_table': 'ActividadEconomica',
            },
        ),
        migrations.CreateModel(
            name='CapacidadEconomica',
            fields=[
                ('id_capacidadEconomica', models.AutoField(primary_key=True, serialize=False, verbose_name='Capacidad Economica ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario')),
                ('gastosAFP', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento de AFP')),
                ('gastosISSS', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento de ISSS')),
                ('gastosPersonales', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos Personales')),
                ('prestamos', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prestamos Bancarios')),
                ('gastosEducacion', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos de Educacion')),
                ('otrosIngresos', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Ingresos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Capacidad Econoomica')),
            ],
            options={
                'db_table': 'CapacidadEconomica',
                'ordering': ['id_capacidadEconomica'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Cliente ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('identificacion', models.CharField(max_length=20, verbose_name='N° de identificacion')),
                ('fecha_nacimiento', models.DateField(help_text='Consejo: <em>Presione en el calendario</em>.', validators=[cliente.models.validar_edad], verbose_name='Fecha de nacimiento')),
                ('telefono', phone_field.models.PhoneField(max_length=13)),
                ('correo', models.EmailField(max_length=35)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('es_asociado', models.BooleanField(default=False, verbose_name='Es asociado?')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='situacionLaboral',
            fields=[
                ('id_situacionLaboral', models.AutoField(primary_key=True, serialize=False, verbose_name='Situacion Laboral ID')),
                ('nombre_situacionLaboral', models.CharField(max_length=50, verbose_name='Situacion laboral actual')),
            ],
            options={
                'db_table': 'situacionLaboral',
                'ordering': ['id_situacionLaboral'],
            },
        ),
        migrations.CreateModel(
            name='tipo_Estadocivil',
            fields=[
                ('id_tipoEstadocivil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipoEstadocivil', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_estadocivil',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipoIdentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoIdentificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Ubicacioneografica',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Ubicacion ID')),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'ubicacion_google',
                'ordering': ['id_ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Solicitud ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_resolocion', models.DateField(default='1000-01-01')),
                ('es_aprobado', models.BooleanField(default=False, verbose_name='Es aprobado?')),
                ('id_actividadEconomica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.actividadeconomica')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
            ],
            options={
                'db_table': 'solicitud',
                'ordering': ['id_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='estado_civil',
            fields=[
                ('id_estadocivil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estado Civil')),
                ('nombres_conyugue', models.CharField(max_length=30, null=True)),
                ('apellidos_conyugue', models.CharField(max_length=30, null=True)),
                ('telefono', phone_field.models.PhoneField(max_length=13, null=True)),
                ('id_tipoEstadocivil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipo_estadocivil', verbose_name='Estado civil')),
            ],
            options={
                'db_table': 'estado_civil',
                'ordering': ['id_estadocivil'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False, verbose_name='Domicilio ID')),
                ('tiempo_de_inmueble', models.PositiveIntegerField(verbose_name='Tiempo de inmueble')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'domicilio',
                'ordering': ['id_domicilio'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_estadocivil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.estado_civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.genero', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipoIdentificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipoidentificacion', verbose_name='Tipo de identificacion'),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='id_capacidadEconomica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.capacidadeconomica', verbose_name='Capacidad Economica'),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='situacionLaboral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.situacionlaboral', verbose_name='Situacion laboral actual'),
        ),
    ]
