# Generated by Django 4.1.2 on 2022-10-17 08:14

import cliente.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Cliente ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('identificacion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(help_text='Usar el formato: <em>YYYY-MM-DD</em>.', validators=[cliente.models.validar_edad], verbose_name='Fecha de nacimiento')),
                ('telefono', phone_field.models.PhoneField(max_length=13)),
                ('correo', models.EmailField(max_length=30)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('es_asociado', models.BooleanField(default=False, verbose_name='Es asociado?')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipoIdentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoIdentificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Solicitud ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_resolocion', models.DateField(default='01/01/1000')),
                ('es_aprobado', models.BooleanField(default=False, verbose_name='Es aprobado?')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
            ],
            options={
                'db_table': 'solicitud',
                'ordering': ['id_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.genero', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipoIdentificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.tipoidentificacion', verbose_name='Tipo de identificacion'),
        ),
    ]
