# Generated by Django 4.1.2 on 2022-10-16 09:38

import cliente.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False, verbose_name='Cliente ID')),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Cliente ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('identificacion', models.CharField(max_length=50)),
                ('XDXDXD', models.TimeField(verbose_name='Fecha de nacimiento')),
                ('googleMap', models.CharField(max_length=50, verbose_name='Api Google Maps')),
                ('localidad', models.CharField(max_length=50, verbose_name='Barrio, Colonia etc.')),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('correo', models.EmailField(max_length=50)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('fecha_nacimiento', models.IntegerField(help_text='Usar el formato: <em>YYYY-MM-DD</em>.', validators=[cliente.models.validar_edad])),
                ('id_genero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.genero', verbose_name='Genero')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['id_cliente'],
            },
        ),
    ]
