# Generated by Django 4.1.2 on 2022-10-20 07:49

import cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacioneografica',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Ubicacion ID')),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'ubicacion_google',
                'ordering': ['id_ubicacion'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Consejo: <em>Presione en el calendario</em>.', validators=[cliente.models.validar_edad], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=20, verbose_name='N° de identificacion'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_resolocion',
            field=models.DateField(default='1000-01-01'),
        ),
    ]
