# Generated by Django 4.1.2 on 2022-11-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='porcentaje',
            field=models.IntegerField(blank=True),
        ),
    ]
