# Generated by Django 4.1.2 on 2022-10-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='id_pais',
            new_name='pais',
        ),
    ]
