# Generated by Django 4.1.2 on 2022-10-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='XDXDXD',
            new_name='fecha_nac',
        ),
    ]
