# Generated by Django 4.1.2 on 2022-10-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_actividadEconomica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.actividadeconomica'),
        ),
    ]
