# Generated by Django 4.1.2 on 2022-10-22 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False, verbose_name='Domicilio ID')),
                ('tiempo_de_inmueble', models.IntegerField(verbose_name='Tiempo de inmueble')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'domicilio',
                'ordering': ['id_domicilio'],
            },
        ),
    ]
