# Generated by Django 4.1.2 on 2022-10-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_profesion', models.AutoField(primary_key=True, serialize=False, verbose_name='Profesion ID')),
                ('nombre_profesion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profesion',
                'ordering': ['id_profesion'],
            },
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='id_profesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.profesion', verbose_name='Profesion'),
            preserve_default=False,
        ),
    ]
