# Generated by Django 4.1.2 on 2022-10-16 10:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_xdxdxd_cliente_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nac',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Extension'),
        ),
    ]
