# Generated by Django 4.1.2 on 2022-10-26 03:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_domicilio_region_alter_domicilio_subregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='pais',
            new_name='id_pais',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='pais',
            new_name='id_pais',
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='id_pais', chained_model_field='id_pais', on_delete=django.db.models.deletion.PROTECT, to='cliente.region', verbose_name='Region'),
        ),
    ]
