# Generated by Django 4.1.2 on 2022-10-16 11:18

import cliente.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_fecha_nac_alter_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Usar el formato: <em>YYYY-MM-DD</em>.', validators=[cliente.models.validar_edad], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
