# Generated by Django 4.1.2 on 2022-10-20 03:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_actividadeconomica_id_capacidadeconomica'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadeconomica',
            name='es_empresario',
            field=models.BooleanField(default=False, verbose_name='Es asociado?'),
        ),
        migrations.AddField(
            model_name='capacidadeconomica',
            name='gastosISSS',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento de ISSS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='id_capacidadEconomica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.capacidadeconomica', verbose_name='Capacidad Economica'),
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='id_profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.profesion', verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='lugarTrabajo',
            field=models.CharField(max_length=50, verbose_name='Lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='telefono',
            field=phone_field.models.PhoneField(max_length=13, verbose_name='Telefono de lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='gastosAFP',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento de AFP'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='gastosEducacion',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos de Educacion'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='gastosPersonales',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos Personales'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='otrosIngresos',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Ingresos'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='prestamos',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prestamos Bancarios'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='capacidadeconomica',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Capacidad Econoomica'),
        ),
    ]
