# Generated by Django 4.1.2 on 2022-10-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_domicilio_region_alter_domicilio_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=35, unique=True),
        ),
    ]
