# Generated by Django 4.1.2 on 2022-10-29 03:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadeconomica',
            name='ciudadTrabajo',
        ),
        migrations.RemoveField(
            model_name='actividadeconomica',
            name='paisTrabajo',
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='localidad',
            field=models.CharField(default=1, help_text='<em>Colonia, Ubanizacion, etc.</em>.', max_length=50, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.pais', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pais', chained_model_field='pais', default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.region', verbose_name='Region / Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadeconomica',
            name='subRegion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.subregion', verbose_name='Sub-Region / Ciudad'),
            preserve_default=False,
        ),
    ]
