# Generated by Django 4.1.2 on 2022-10-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_remove_actividadeconomica_ciudadtrabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='es_revisado',
            field=models.BooleanField(default=False, verbose_name='Es revisado?'),
        ),
    ]
