# Generated by Django 4.1.2 on 2022-10-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_solicitud_es_revisado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Ubicacion ID')),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
