# Generated by Django 4.1.2 on 2022-10-29 06:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_ubicaciongeografica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_civil',
            name='apellidos_conyugue',
            field=models.CharField(help_text='Ayuda: <em>Solo ingresar estos datos si está casado o comprometido.</em>.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estado_civil',
            name='nombres_conyugue',
            field=models.CharField(help_text='Ayuda: <em>Solo ingresar estos datos si está casado o comprometido.</em>.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estado_civil',
            name='telefono',
            field=phone_field.models.PhoneField(help_text='Ayuda: <em>Solo ingresar estos datos si está casado o comprometido.</em>.', max_length=13, null=True),
        ),
    ]
