# Generated by Django 4.1.2 on 2022-10-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_parentesco_referenciapersonal_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.ImageField(upload_to='fotografias/', verbose_name='DUI')),
                ('nit', models.ImageField(upload_to='fotografias/', verbose_name='NIT')),
                ('pasaporte', models.ImageField(upload_to='fotografias/', verbose_name='Pasaporte')),
                ('isss', models.ImageField(upload_to='fotografias/', verbose_name='Tarjeta ISSS')),
                ('iva', models.ImageField(upload_to='fotografias/', verbose_name='Tarjeta IVA')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitud')),
            ],
            options={
                'db_table': 'anexo',
                'ordering': ['id_anexo'],
            },
        ),
    ]
