# Generated by Django 4.1.2 on 2022-10-30 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='es_validado',
            field=models.BooleanField(default=False, verbose_name='Es validado?'),
        ),
        migrations.AlterField(
            model_name='referenciapersonal',
            name='parentesco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.parentesco', verbose_name='Parentesco'),
        ),
    ]
